### PR TITLE
cmd/servegoissues: Display link to view original issue.

### LINKED ISSUE #9: cmd/servegoissues: add a link to the original issue
I want to comment on the issue when I have Internet and a link to the original thread would be awesome to have.

I also don't understand the functionality of the commenting button under each issue. It doesn't work at all. Remove and replace with a link to the original issue?

### PR DESCRIPTION
**Pull request by dmitshur**
Previously, it would display a "Sign in to comment" message which was not applicable to this view-only Go issue viewer. User logins are not supported here. Even if they were, it wouldn't make sense to post new comments to a mirror of Go issues.

Before:

image

After:

image

Resolves #9. /cc @rakyll

### CODE REVIEW

File: cmd/servegoissues/servegoissues.go [hunk 1]
```diff
@@ -76,6 +76,11 @@ func main() {
 		box-shadow: 0 1px 1px rgba(0, 0, 0, .05);
 	}
 </style>`,
+		BodyPre: `
+{{/* Override new comment component to link to original issue for leaving comments. */}}
+{{define "new-comment"}}<div class="event" style="margin-top: 20px; margin-bottom: 100px;">
+	View <a href="https://github.com/golang/go/issues/{{.Issue.ID}}#new_comment_field">original issue</a> to comment.
```
Comment (dmitshur) [inline cmd/servegoissues/servegoissues.go:82]: This currently hardcodes `golang/go` here and assumes github.com issue tracker. I think it's valid for serve**go**issues and we should merge this as is. However, for https://github.com/bradfitz/go-issue-mirror/issues/7#issuecomment-242991322, we can refactor this to use the `RepoSpec` and generate a valid link to whichever repository/issue tracker it corresponds to.

I'd rather defer doing that until then because it'll be easier, given we'll have a better idea of the requirements and assumptions we can make. Will it support github-only projects? Or others too? That'll be important to know.

**Comment by dmitshur** [comment]
Friendly ping. Is there anything this PR needs from me to get to a state where it can be merged?
